CREATE TABLE IF NOT EXISTS `creation_project_bgm_binding` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
  `biz_id` BIGINT UNSIGNED NOT NULL COMMENT '业务主键(雪花ID)',
  `project_id` VARCHAR(64) NOT NULL COMMENT '创作项目ID',
  `version_id` VARCHAR(64) NULL COMMENT '可选编排版本ID',
  `audio_id` VARCHAR(128) NOT NULL COMMENT 'BGM资产逻辑ID',
  `audio_name` VARCHAR(255) NULL COMMENT 'BGM展示名称',
  `src_path` VARCHAR(1024) NOT NULL COMMENT '最终供Remotion/FFmpeg使用的源路径',
  `preview_url` VARCHAR(1024) NULL COMMENT '前端可直接预览/回放的URL',
  `source_type` VARCHAR(32) NOT NULL COMMENT 'RECOMMENDED/MANUAL_UPLOAD/MANUAL_PICK',
  `recommend_score` DOUBLE NULL COMMENT '推荐最终得分',
  `semantic_score` DOUBLE NULL COMMENT '语义匹配子分',
  `energy_curve_score` DOUBLE NULL COMMENT '能量曲线匹配子分',
  `duration_bpm_score` DOUBLE NULL COMMENT '时长/BPM匹配子分',
  `mix_level` VARCHAR(32) NOT NULL COMMENT '语义混音档位: QUIET/BALANCED/DRIVE',
  `volume` DOUBLE NOT NULL COMMENT '后端计算后的最终执行音量',
  `loop_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否循环播放',
  `fade_in_frames` INT NOT NULL DEFAULT 15 COMMENT '淡入帧数',
  `fade_out_frames` INT NOT NULL DEFAULT 30 COMMENT '淡出帧数',
  `ducking_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否允许对该BGM做闪避',
  `ducking_ratio` DOUBLE NULL COMMENT '闪避比例，如0.2',
  `metadata_json` JSON NULL COMMENT '扩展元信息，如bpm/style/duration等',
  `status` VARCHAR(32) NOT NULL COMMENT 'SELECTED/REPLACED/DISABLED',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL COMMENT '逻辑删除时间',

  CONSTRAINT `uk_creation_project_bgm_binding_biz_id` UNIQUE (`biz_id`),
  KEY `idx_creation_project_bgm_project_status` (`project_id`, `status`),
  KEY `idx_creation_project_bgm_audio_id` (`audio_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='创作项目当前BGM绑定表';
