package com.bytedance.aivideo.infrastructure.ark;

/**
 * 方舟提示词模板集中维护类。
 * 约定：ASR/OCR/LLM 相关提示词统一在这里维护，避免分散硬编码。
 */
public final class ArkPromptTemplates {

        private ArkPromptTemplates() {
        }

        /**
         * ASR 基础提示词：要求输出统一 JSON 结构，便于直接入库。
         */
        public static final String ASR_TRANSCRIBE_JSON = "请识别这段音频内容，并进行逐句时间轴切分，同时为每个句段输出音频语义标签。"
                        + "你必须仅输出一个合法 JSON 对象，不要输出解释文本、不要输出 Markdown 代码块。"
                        + "你必须输出原句文案，如果存在英文，不要翻译。"
                        + "输出结构必须包含 fullText 和 segments。"
                        + "segments 必须按时间升序，且每个 segment 必须包含：segmentIndex、start、end、text、speaker、confidence、audioEmotion、volumeIntensity、backgroundEnvironment、vocalVibe、bgmGenre、bgmInstruments。"
                        + "start/end 单位为秒，end 必须大于 start。"
                        + "speaker 推荐值 SPEAKER_1/SPEAKER_2，无法区分时填 UNKNOWN。"
                        + "confidence 取值范围 0 到 1。"
                        + "audioEmotion 枚举：CALM、CURIOUS、AGITATED、EXCITED、URGENT、NONE。"
                        + "【音量烈度物理锚定（volumeIntensity）】：严禁仅凭声音清晰度判断！必须基于人类发声物理行为："
                        + "LOW(窃窃私语/极小声)、"
                        + "MEDIUM(正常的面对面平稳交谈/常规解说口播)、"
                        + "HIGH(明显提高音量的喊叫/激烈的争吵/高昂的演讲)、"
                        + "PEAK(情绪失控的咆哮/震耳欲聋的物理爆破音)。"
                        + "注：如果只是清晰的常规口播，绝对不允许使用 HIGH！"
                        + "backgroundEnvironment 枚举："
                        + "MUSIC(背景音乐为主)、"
                        + "FX(特殊音效为主，如转场音/点击音/爆点音/笑声等)、"
                        + "MUSIC_FX(背景音乐与特殊音效同时明显存在)、"
                        + "NOISE(环境噪声为主)、"
                        + "SILENT(近静音或仅极弱环境声)。"
                        + "vocalVibe：不能仅依靠字面意思，必须通过听觉判断说话人的情绪张力，并用一句自然语言精准描述；若无人声填空字符串。"
                        + "bgmGenre：若存在背景音乐，必须忽略人声干扰，听辨并输出音乐流派；若无音乐填空字符串。"
                        + "bgmInstruments：若存在背景音乐，听辨并输出最突出的乐器组合；若无音乐填空字符串。"
                        + "若无人声片段，text 可为空字符串，但语义字段必须填写。"
                        + "输出示例："
                        + "{\"fullText\":\"\",\"segments\":[{\"segmentIndex\":0,\"start\":0.0,\"end\":1.0,\"text\":\"\",\"speaker\":\"SPEAKER_1\",\"confidence\":0.99,\"audioEmotion\":\"CURIOUS\",\"volumeIntensity\":\"MEDIUM\",\"backgroundEnvironment\":\"MUSIC\",\"vocalVibe\":\"压抑克制的低语\",\"bgmGenre\":\"悬疑底噪\",\"bgmInstruments\":\"低频合成器与弱打击乐\"}]}";

        /**
         * ASR 二次重试提示词后缀：仅做格式修正。
         */
        public static final String STRICT_JSON_SUFFIX = "仅输出JSON，不要包含解释、代码块标记或其他文本。";

        /**
         * 视频拆解结构大一统分析提示词。
         */
        public static final String STRUCTURE_ANALYZER_UNIFIED = "你现在是短视频结构拆解专家。请阅读系统为你对齐后的【多模态时序剧本】以及可选的【视频关键帧图片】。\n"
                        + "时序剧本中若出现【IMAGE_001】这类标记，表示对应消息中按顺序提供的关键帧图片；IMAGE 编号与图片输入顺序严格一一对应。\n\n"
                        + "关键帧现在可能带有角色说明，例如 `HOOK_START`、`HOOK_MID`、`CUT_BEFORE`、`CUT_AFTER`、`LONG_SHOT_MID`、`UNIFORM_COVERAGE`。\n"
                        + "你必须结合这些角色说明与相邻关键帧的前后变化理解镜头切换、段落推进和包装密度变化，禁止只根据单张画面做静态总结。\n\n"
                        + "任务目标：\n"
                        + "1. 判定视频品类（查表已知或自动发现新品类）。\n"
                        + "2. 产出一个 JSON，包含该视频的「脚本结构」、「节奏结构」、「包装结构」和「动态特征矩阵」。\n\n"
                        + "--- 视频多模态时序日志 (Markdown 剧本格式) ---\n"
                        + "%s\n\n" // 占位符 1：注入由 TimelineMatcher 内存聚合生成的全量胖剧本流
                        + "【已知品类知识库参考】\n"
                        + "说明：该参考区展示的是品类知识库中的字段定义层，只包含字段名、字段类型、字段说明，以及可选的允许枚举池；这些内容不是历史样例值。\n"
                        + "若参考区中的字段显示为 `fieldName (fieldType)` 或附带 `allowedValues`，你必须严格沿用同名字段的 fieldType；若存在 `allowedValues`，当前输出的 fieldValue 必须从该候选池中选择。\n"
                        + "%s\n\n" // 占位符 2：注入来自向量库 ChromaDB / MySQL 的类别特征种子数据
                        + "【动态特征自进化与覆写契约（核心铁律）】\n"
                        + "在输出最终的 `categoryExtensions.dynamicExtensionFields` JSON 数组时，你必须严格执行以下增量进化逻辑：\n"
                        + "1. 刚性继承（Inherit）：若当前判定品类在【已知品类知识库参考】中存在，必须将该品类已定义的核心 fieldName 原样带入数组，严禁遗漏。\n"
                        + "2. 动态修正（Update）：必须依据当前视频多模态表现重新独立测算上述字段值；若突破历史经验，必须输出修正后的最新 fieldValue。\n"
                        + "3. 盲区发现（Insert）：若发现知识库尚未定义的高优特征（如新剪辑手法、特殊情绪、特有调色），必须主动新增 fieldName（小写英文 snake_case 命名）并追加到数组。\n"
                        + "4. 格式封死：所有提取、修正与新增特征，必须且只能使用 JSON 对象格式"
                        + " `{ \"fieldName\": \"...\", \"fieldType\": \"...\", \"fieldValue\": \"...\", \"description\": \"...\" }`"
                        + " 放在该数组内，禁止在 JSON 外输出解释。\n"
                        + "5. fieldType 枚举约束：必须且只能使用 `STRING`、`DOUBLE`、`INTEGER`、`BOOLEAN`、`JSON`。\n"
                        + "6. fieldName 命名约束：必须使用小写英文 snake_case 命名，长度 2~64，仅允许小写字母、数字和下划线，且必须以字母开头，禁止空格、中文和其他特殊符号。\n"
                        + "7. 新增字段上限：除继承字段外，单次最多新增 5 个新 fieldName，超出时仅保留最关键的前 5 个。\n"
                        + "8. 新字段说明硬约束：若输出知识库中不存在的新 fieldName，该字段必须同时输出清晰的 `description`。该说明必须解释字段的抽象含义、适用场景或统计意义，要求可迁移、可复用；禁止在 description 中写具体人物、地点、剧情、品牌或当前样例专属内容。若新字段缺少 description，则该字段视为无效。\n"
                        + "9. 若某个新字段天然存在固定候选池或有限枚举（例如常用特效列表），你可以额外输出可选键 `allowedValues`，其值必须是 JSON 数组；否则不要输出该键。\n"
                        + "10. 命名规范：若 `fieldValue` 或 `allowedValues` 表示的是策略枚举、风格枚举、标签标识或其他机器可消费的离散候选值，必须优先使用小写英文 snake_case；只有自然语言说明型取值才允许使用普通文本。\n\n"
                        + "【宏观品类命名与发现铁律】\n"
                        + "当判定当前视频属于新品类并需要创造新的 category 时，必须遵守宏观行业分类原则：\n"
                        + "1. 品类颗粒度必须是宏观的（如 `short_drama`、`vlog`、`gameplay`、`tutorial`、`product_review`）。\n"
                        + "2. 绝对不允许将具体地点/具体事件/具体人物作为品类名。\n"
                        + "3. 错误示范：`school_canteen_drama`、`car_review`。\n"
                        + "4. 正确归类：上述两者应分别归入 `short_drama` 和 `product_review`。\n\n"
                        + "【数据实体边界隔离铁律（极其重要）】\n"
                        + "你必须严格区分模板微观特征与品类宏观特征：\n"
                        + "1. 模板微观特征（仅留在模板层）：凡是当前视频特有的具体信息（具体场景地点、具体人物、特定台词），只能写入 `meta.description`、`meta.styles`、`viralFactors`，以及少量代表性 `shots` 原型。\n"
                        + "2. 品类宏观特征（仅进入知识库层）：写入 `categoryExtensions.dynamicExtensionFields` 的内容，必须是抽象且可复用的行业规则或统计学特征（如切分阈值、镜头运动偏好、卡点策略、节奏分布）。\n"
                        + "3. 严禁污染：绝对不允许将具体场景、具体剧情、具体人名写入 `dynamicExtensionFields` 的 `fieldName`、`fieldValue` 或 `description`。\n\n"
                        + "【刚性结构与字段类型契约（通用化限制，严禁自由发挥与虚构）】\n"
                        + "1. `scriptStructure.segments[].role` 必须且只能从以下全视频通用骨架枚举中选择：\n"
                        + "   - `hook` | `body` | `climax` | `outro`\n"
                        + "   任何视频均只允许由这四个通用骨架组合，禁止出现特定品类业务专有 role。\n\n"
                        + "【平铺直叙与结构坍塌逃生契约】：\n"
                        + "   - 警告：并非所有视频都存在 climax！对于平淡的参数测评、纯口播、白板教学等缺乏非线性波动的视频，允许且强烈建议采用 `hook` + 多个 `body` + `outro` 的平流层组合。\n"
                        + "   - 只有当视频在声学（情绪爆发/重低音）或视觉（高频快闪/强对比）上出现真正的绝对峰值时，才允许使用 `climax`。\n"
                        + "   - 严禁在无明显波动的视频中，利用微弱的相对极值强行捏造 climax！\n\n"
                        + "2. `rhythmStructure.overallPace` 和 `paceCurve[].pace` 必须且只能从以下节奏等级枚举中选择：\n"
                        + "   - `slow` | `medium` | `fast` | `very_fast` | `ultra_fast`\n\n"
                        + "3. `rhythmStructure.beatSyncPoints[].type` 必须且只能从以下卡点类型枚举中选择：\n"
                        + "   - `visual_hit` | `audio_hit` | `climax_hit`\n\n"
                        + "4. 品类身份特征仅允许在 `categoryExtensions.dynamicExtensionFields` 内扩展：\n"
                        + "   - 如需表达品类细分段落语义，只能以 KEY-VALUE 形式扩展，禁止污染通用骨架字段。\n"
                        + "   - 示例：`{ \"fieldName\": \"segment_1_actual_role\", \"fieldType\": \"STRING\", \"fieldValue\": \"skill_deconstruction\" }`\n\n"
                        + "5. 数据格式与硬性匹配约束（极重要）：\n"
                        + "   - `meta.acousticEnvironment` 必须且只能从枚举 `asmr`|`quiet`|`noisy`|`speech_focused`|`music_driven` 中选择，此字段用于后续音频匹配的物理环境 Veto 校验。\n"
                        + "   - `scriptStructure.segments[]` 允许新增以下抽象视觉执行字段：`preferredShotTypes`、`preferredCameraMovements`、`requiredVisualFunctions`、`subtitleStrategy`、`packagingDensity`、`fallbackStrategies`。\n"
                        + "   - `preferredShotTypes` 数组元素必须且只能从 `CLOSE_UP`|`MID_SHOT`|`WIDE_SHOT`|`UNKNOWN` 中选择；`preferredCameraMovements` 数组元素必须且只能从 `STATIC`|`ZOOM_IN`|`ZOOM_OUT`|`PAN`|`UNKNOWN` 中选择。\n"
                        + "   - `requiredVisualFunctions` 推荐且优先使用：`subject_intro`|`detail_showcase`|`usage_process`|`emotion_push`|`proof_or_comparison`|`benefit_recall`|`cta_prompt`|`static_summary_card`。\n"
                        + "   - `subtitleStrategy` 必须且只能从 `none`|`sparse`|`guided`|`dense` 中选择；`packagingDensity` 必须且只能从 `none`|`low`|`medium`|`high` 中选择。\n"
                        + "   - `fallbackStrategies` 推荐且优先使用：`reorder_structure`|`text_overlay_replace`|`packaging_emphasis`|`reuse_existing_material`|`static_summary_card`。\n"
                        + "   - `shots[].shotType` 必须明确指出物理视角，推荐枚举：`face_closeup`|`first_person`|`top_down`|`full_body`|`mid_shot`|`wide_shot` 等，用于空间逻辑校验。\n"
                        + "   - `shots[].shotTypeTag` 必须且只能从 `CLOSE_UP`|`MID_SHOT`|`WIDE_SHOT` 中选择；`shots[].cameraMovementTag` 必须且只能从 `STATIC`|`ZOOM_IN`|`ZOOM_OUT`|`PAN` 中选择。若无法判断可填 `UNKNOWN`。\n"
                        + "   - `shots` 仅允许输出少量代表性镜头原型，数量建议 <= 6；优先输出 `functionHint`，禁止长篇复述具体地点、人物、剧情、品牌名或台词细节。\n"
                        + "   - `weight`、`durationWeight` 必须是 [0.0,1.0] 的 DOUBLE，严禁百分号或字符串。\n"
                        + "   - `timePercent` 必须是 [0,100] 的 INTEGER，严禁百分号。\n"
                        + "   - `requiredContent` 中的内容必须是高度抽象且具有通用性的，绝对不能出现任何真实产品、特定IP、品牌名或具体人名的信息（否则后续AI缺口补全生图时会出现很大偏差）。例如：包装手法类不能写“米老鼠贴纸”，必须抽象为“生动、可爱的卡通贴纸”；内容主体类不能写“苹果手机”，应高度抽象为“目标产品”。\n"
                        + "   - `titleCards`、`transitions` 等若不存在，必须输出空数组 `[]`，禁止缺失键名或赋值 `null`。\n"
                        + "   - 所有涉及颜色(color)的字段，必须严格输出 16 进制格式（例如 `#FFFFFF`）。\n\n"
                        + "6. 关键帧阅读约束：\n"
                        + "   - `HOOK_START` / `HOOK_MID` 优先用于判断开头 hook 的建立方式、主体进入方式与初始构图。\n"
                        + "   - `CUT_BEFORE` / `CUT_AFTER` 必须成对理解，用于判断镜头切换频率、切换前后语义跳变、节奏推进与高潮位置。\n"
                        + "   - `LONG_SHOT_MID` 用于补充长镜头内部动作、镜头推进与包装元素的持续变化。\n"
                        + "   - `UNIFORM_COVERAGE` 用于补足全片分布，帮助你判断中段展开、结尾收束与整体节奏曲线。\n"
                        + "   - 你必须优先利用关键帧之间的连续变化来判断 `hook / body / climax / outro`、段落快慢变化和包装密度变化，禁止仅凭单点静态内容生硬归类。\n\n"
                        + "【多模态双语对齐约束】\n"
                        + "ASR 文本与关键帧视觉元素可能出现中英文并存，这是同一意图的多模态呈现。"
                        + "禁止因为语言不一致而误判包装缺陷；应做语义对齐后再抽象模板。\n\n"
                        + "【视觉固定噪声与平台水印刚性过滤】\n"
                        + "若关键帧存在平台标识、作者昵称、账号ID、头像、签名或其他个人信息水印，必须视为固定噪声并完全忽略。"
                        + "严禁在 JSON 任何字段中输出、转述、映射或变体记录这些水印信息。\n\n"
                        + "输出 JSON 格式要求：\n"
                        + "必须仅输出一个合法 JSON 对象（不要输出 Markdown 标记），结构必须符合 `video-structure-template/v2` 协议：\n"
                        + "{\n"
                        + "  \"$schema\": \"video-structure-template/v2\",\n"
                        + "  \"templateId\": \"自动生成一个UUID\",\n"
                        + "  \"templateName\": \"为该视频总结一个高概括性的模板名称\",\n"
                        + "  \"version\": \"1.0.0\",\n"
                        + "  \"category\": \"如果是已知品类填对应ID；如果是新品类，必须使用宏观行业分类的 snake_case ID（例如 short_drama/product_review）\",\n"
                        + "  \"meta\": {\n"
                        + "    \"targetDuration\": { \"min\": 25, \"max\": 35, \"unit\": \"seconds\" },\n"
                        + "    \"aspectRatio\": \"9:16\",\n"
                        + "    \"resolution\": { \"width\": 1080, \"height\": 1920 },\n"
                        + "    \"acousticEnvironment\": \"asmr\",\n"
                        + "    \"styles\": [\"LLM 自动归纳的风格描述1\", \"风格描述2\"],\n"
                        + "    \"description\": \"模板来源与特征概述\"\n"
                        + "  },\n"
                        + "  \"scriptStructure\": {\n"
                        + "    \"totalSegments\": 4,\n"
                        + "    \"segments\": [\n"
                        + "      { \"segmentIndex\": 0, \"role\": \"hook\", \"label\": \"名称\", \"description\": \"段落功能描述\", \"durationRange\": { \"min\": 2, \"max\": 4 }, \"durationWeight\": 0.12, \"scriptHint\": \"文案提示\", \"requiredElements\": [], \"shotCount\": { \"min\": 1, \"max\": 2 }, \"subSegments\": [], \"preferredShotTypes\": [\"CLOSE_UP\"], \"preferredCameraMovements\": [\"STATIC\", \"ZOOM_IN\"], \"requiredVisualFunctions\": [\"subject_intro\"], \"subtitleStrategy\": \"guided\", \"packagingDensity\": \"medium\", \"fallbackStrategies\": [\"text_overlay_replace\"] }\n"
                        + "    ]\n"
                        + "  },\n"
                        + "  \"rhythmStructure\": {\n"
                        + "    \"overallPace\": \"medium\",\n"
                        + "    \"avgShotDuration\": 2.8,\n"
                        + "    \"paceCurve\": [ { \"timePercent\": 0, \"pace\": \"fast\", \"note\": \"说明\" } ],\n"
                        + "    \"climaxPositions\": [ { \"startPercent\": 65, \"endPercent\": 80 } ],\n"
                        + "    \"transitionStyles\": [\"hard_cut_dominant\"],\n"
                        + "    \"beatSyncPoints\": [ { \"timePercent\": 0, \"type\": \"visual_hit\" } ]\n"
                        + "  },\n"
                        + "  \"packagingStructure\": {\n"
                        + "    \"subtitleStyles\": [ { \"position\": \"bottom_center\", \"fontSize\": \"medium\", \"color\": \"#FFFFFF\", \"background\": \"semi_transparent_black\", \"animation\": \"fade_in\" } ],\n"
                        + "    \"titleCards\": [],\n"
                        + "    \"transitions\": [],\n"
                        + "    \"coverStyles\": [ { \"layout\": \"text_left_image_right\", \"textElements\": [\"主标题\"], \"colorTone\": \"#FF8C00\" } ]\n"
                        + "  },\n"
                        + "  \"shots\": [\n"
                        + "    { \"shotIndex\": 0, \"belongsToSegment\": 0, \"shotType\": \"face_closeup\", \"shotTypeTag\": \"CLOSE_UP\", \"functionHint\": \"subject_intro\", \"durationRange\": { \"min\": 2, \"max\": 3 }, \"cameraMovement\": \"static\", \"cameraMovementTag\": \"STATIC\", \"requiredContent\": [] }\n"
                        + "  ],\n"
                        + "  \"categoryExtensions\": {\n"
                        + "    \"discoveredCategoryId\": \"同上的categoryID\",\n"
                        + "    \"discoveredCategoryName\": \"品类中文名\",\n"
                        + "    \"dynamicExtensionFields\": [\n"
                        + "       { \"fieldName\": \"cut_frequency\", \"fieldType\": \"STRING\", \"fieldValue\": \"low_frequency\", \"description\": \"长镜头慢节奏为主，仅关键动态节点做少量硬切\" },\n"
                        + "       { \"fieldName\": \"motion_effects\", \"fieldType\": \"JSON\", \"fieldValue\": [\"slow_motion\"], \"description\": \"该品类常用的镜头运动与特效列表\", \"allowedValues\": [\"speed_ramp\", \"zoom_punch\", \"shake\", \"slow_motion\", \"static_lockoff\", \"extreme_close_up\"] }\n"
                        + "    ],\n"
                        + "    \"discoveredPromptOverrides\": { \"scriptAnalysis\": \"...\" }\n"
                        + "  },\n"
                        + "  \"viralFactors\": [\n"
                        + "    { \"factorName\": \"情绪共鸣\", \"weight\": 0.8, \"description\": \"分析该视频能爆火的原因\" }\n"
                        + "  ]\n"
                        + "}\n"
                        + "特别注意：你必须严格遵循上述 JSON 协议与枚举约束。"
                        + "`dynamicExtensionFields` 用于输出当前视频的观测值；知识库定义层会单独抽取字段名、类型、说明和可选 allowedValues。"
                        + "如果是新发现品类，可以在 `dynamicExtensionFields` 中补充 `scene_threshold` 这类运行时分析 hint，但它不是模板核心字段，也不是必填项。";

        /**
         * 创作素材轻量级原生听觉解析 (PRE-ASR)
         */
        public static final String CREATION_PRE_ASR_PROMPT = "请听这段音频，提取出人声台词与明显的环境音。"
                        + "你必须输出一个格式化 JSON，不要有任何多余解释。"
                        + "JSON 包含 fullText(全文本) 和 segments 数组。"
                        + "segments 数组中每个元素包含 start(秒), end(秒), text(内容)。"
                        + "如果是无台词但有明显环境音的情况，请用括号标出，例如 (纸张摩擦声) 或 (水流声)。过滤掉微弱的底噪。";

        /**
         * 创作素材分析（VIDEO）：多宫格 + ASR 视听联合打标 (Early Fusion)。
         * 占位符：physicalAttributesJson, asrText
         */
        public static final String CREATION_PROFILE_VIDEO_JSON = "你是创作素材分析引擎。当前素材类型为 VIDEO。"
                        + "你将收到按时间顺序排列的多张宫格图，每张图内帧上带时间戳。"
                        + "请结合视觉内容与我提供的 asrText（包含声音流水账），进行视听 Early Fusion 分析，输出用于创作链路的结构化 JSON。"
                        + "仅输出一个合法 JSON，不要输出解释文本或 Markdown。"
                        + "输入 physicalAttributes=%s。"
                        + "输入 asrText=%s。"
                        + "输出必须包含 semanticTags 和 highlights。"
                        + "semanticTags 建议包含：mainEntities,lightVibe,overallStyle,acousticEnvironment,audioVibe,audioDescription,suitableRoles,emotionTone。"
                        + "【重要】你必须在 semanticTags 中严格输出 acousticEnvironment（枚举: asmr/quiet/noisy/speech_focused/music_driven）和 audioDescription（自然语言总结全局音画配合度）。"
                        + "highlights 必须是数组，每个元素建议包含：segmentId,usabilityScore,timeAnchor,shotType,shotTypeTag,actionState,cameraMovement,cameraMovementTag,spokenText,audioContext,spatialAnchor。"
                        + "【重要】你必须在每个 highlight 中同时输出："
                        + "1) 解释字段 shotType/cameraMovement（自然语言，可用于展示）"
                        + "2) 逻辑字段 shotTypeTag/cameraMovementTag（刚性枚举，用于评分）"
                        + "shotTypeTag 枚举只能是 CLOSE_UP|MID_SHOT|WIDE_SHOT；"
                        + "cameraMovementTag 枚举只能是 STATIC|ZOOM_IN|ZOOM_OUT|PAN。"
                        + "若无法判断，tag 必须填 UNKNOWN。"
                        + "timeAnchor 的 startTime/endTime 单位秒，endTime 必须大于 startTime。"
                        + "suitableRoles 只能使用 hook/body/climax/outro。"
                        + "若无法稳定定位 spatialAnchor 可省略该字段，禁止虚构。"
                        + "输出示例："
                        + "{\"semanticTags\":{\"mainEntities\":[\"人物\",\"产品\"],\"lightVibe\":\"balanced\",\"overallStyle\":\"口播展示\",\"acousticEnvironment\":\"quiet\",\"audioVibe\":\"clear_speech\",\"audioDescription\":\"整体环境安静，有轻微背景摩擦声\",\"suitableRoles\":[\"body\",\"outro\"],\"emotionTone\":\"calm\"},"
                        + "\"highlights\":[{\"segmentId\":\"h_01\",\"usabilityScore\":0.88,\"timeAnchor\":{\"startTime\":2.0,\"endTime\":6.5},\"shotType\":\"中景产品展示\",\"shotTypeTag\":\"MID_SHOT\",\"actionState\":\"product_showcase\",\"cameraMovement\":\"由远及近缓慢推镜\",\"cameraMovementTag\":\"ZOOM_IN\",\"spokenText\":\"这款产品非常实用\",\"audioContext\":\"伴随清脆的按键声，人声清晰\","
                        + "\"spatialAnchor\":{\"subject\":\"product\",\"boundingBox\":{\"x\":220,\"y\":300,\"w\":460,\"h\":520}}}]}";

        /**
         * 创作素材分析（IMAGE）：静态图空间锚点打标。
         * 占位符：physicalAttributesJson
         */
        public static final String CREATION_PROFILE_IMAGE_JSON = "你是创作素材分析引擎。当前素材类型为 IMAGE。"
                        + "请基于输入图片输出结构化 JSON，仅输出一个合法 JSON，不要解释。"
                        + "输入 physicalAttributes=%s。"
                        + "输出必须包含 semanticTags 和 highlights。"
                        + "semanticTags 建议包含：mainEntities,lightVibe,overallStyle,suitableRoles,emotionTone。"
                        + "highlights 应为静态高光数组，可包含 segmentId,usabilityScore,shotType,shotTypeTag,actionState,cameraMovement,cameraMovementTag,spatialAnchor。"
                        + "请尽量稳定输出主体的 spatialAnchor.boundingBox，后续 LOCAL_BLUR 与 KEN_BURNS_MOTION 会直接复用该主体框。"
                        + "【重要】你必须在每个 highlight 中同时输出 shotType/cameraMovement（自然语言）和 shotTypeTag/cameraMovementTag（刚性枚举）。"
                        + "shotTypeTag 枚举只能是 CLOSE_UP|MID_SHOT|WIDE_SHOT；cameraMovementTag 枚举只能是 STATIC|ZOOM_IN|ZOOM_OUT|PAN；无法判断填 UNKNOWN。"
                        + "IMAGE 不允许输出 timeAnchor。"
                        + "suitableRoles 只能使用 hook/body/climax/outro。"
                        + "输出示例："
                        + "{\"semanticTags\":{\"mainEntities\":[\"饮品\",\"品牌logo\"],\"lightVibe\":\"bright\",\"overallStyle\":\"清新电商图\",\"suitableRoles\":[\"hook\",\"outro\"],\"emotionTone\":\"pleasant\"},"
                        + "\"highlights\":[{\"segmentId\":\"h_01\",\"usabilityScore\":0.93,\"shotType\":\"产品近景特写\",\"shotTypeTag\":\"CLOSE_UP\",\"actionState\":\"static_display\",\"cameraMovement\":\"静态陈列\",\"cameraMovementTag\":\"STATIC\",\"spatialAnchor\":{\"subject\":\"drink\",\"boundingBox\":{\"x\":180,\"y\":240,\"w\":720,\"h\":980}}}]}";

        /**
         * 创作素材分析（TEXT）：文本语义与包装打标。
         * 占位符：physicalAttributesJson, textContent
         */
        public static final String CREATION_PROFILE_TEXT_JSON = "你是创作素材分析引擎。当前素材类型为 TEXT。"
                        + "请根据输入文本输出结构化 JSON，仅输出一个合法 JSON，不要解释。"
                        + "输入 physicalAttributes=%s。"
                        + "输入 textContent=%s。"
                        + "输出必须包含 semanticTags 和 highlights。"
                        + "semanticTags 必须重点给出：textCategory,mainKeywords,suitableRoles,overallStyle,emotionTone。"
                        + "highlights 应使用 textContent 和 textType（title_overlay 或 normal_subtitle）描述文本高光。"
                        + "TEXT 不允许输出 timeAnchor 或 spatialAnchor。"
                        + "suitableRoles 只能使用 hook/body/climax/outro。"
                        + "输出示例："
                        + "{\"semanticTags\":{\"textCategory\":\"hook_question\",\"mainKeywords\":[\"免费\",\"技巧\"],\"suitableRoles\":[\"hook\"],\"overallStyle\":\"强吸引文案\",\"emotionTone\":\"urgent\"},"
                        + "\"highlights\":[{\"segmentId\":\"t_01\",\"usabilityScore\":1.0,\"textContent\":\"99%%的人都忽略了这个免费技巧\",\"textType\":\"title_overlay\"}]}";

        /**
         * 创作槽位匹配：模板快照 + 素材画像 -> 缺口识别与适配方案。
         * 占位符：projectId, versionId, templateSnapshotJson, materialProfilesJson
         */
        public static final String CREATION_SLOT_MATCH_JSON = "你是视频创作链路的槽位匹配与素材缺口识别引擎。"
                        + "你的任务是把模板的每个 scriptStructure.segments[] 槽位，与用户素材画像进行匹配，并输出可执行的 adaptationPlan。"
                        + "你必须仅输出一个合法 JSON 对象，不要输出 Markdown 或解释文本。"
                        + "projectId=%s。versionId=%s。"
                        + "目标视频画面比例 targetAspectRatio=%s。"
                        + "用户项目描述 projectDescription=%s。"
                        + "模板快照 templateSnapshotJson=%s。"
                        + "素材画像 materialProfilesJson=%s。"
                        + "【硬性规则】"
                        + "1. matchDecisions 必须覆盖模板中每一个 segment，且 segmentIndex 必须与模板一致。"
                        + "2. 必须充分解读模板的 viralFactors（爆款灵魂）与 categoryExtensions（品类特征）。素材匹配不应仅停留在客观镜头对齐，必须优先挑选能传达爆款情绪氛围的素材；对完美契合爆款灵魂的素材，应给予极高的 matchScore。"
                        + "3. matchStatus 只能是 MATCHED、PARTIAL、MISSING、VETOED。"
                        + "4. matchedAssetId 必须来自 materialProfilesJson 中的 materialBizId；MISSING/VETOED 时填空字符串。"
                        + "5. matchedHighlightId 应来自素材 highlights[].segmentId；若无法定位填空字符串。"
                        + "6. strategyType 只能使用 TRIM_AND_CUT、SMART_CROP、LIGHTING_ADJUST、LOCAL_BLUR、LOOP_SEQUENCE、KEN_BURNS_MOTION。"
                        + "7. MISSING/VETOED 的 adaptationPlan.strategyChain 必须为空数组，并必须填写 vetoReason。"
                        + "8. VIDEO 素材优先使用 TRIM_AND_CUT；需要画幅适配时可追加 SMART_CROP；若 physicalAttributes.lighting 表明亮度或对比度存在明显问题，可追加 LIGHTING_ADJUST。"
                        + "9. IMAGE 素材若用于视频段，优先使用 KEN_BURNS_MOTION；若需突出主体、弱化背景且存在稳定 spatialAnchor.boundingBox，可在 KEN_BURNS_MOTION 之前追加 LOCAL_BLUR；需要补时长时可追加 LOOP_SEQUENCE。"
                        + "10. 保护类图像资产（如 LOGO、品牌标识、插图、挂件图、角标、贴纸、图标）只允许分析、匹配和后续 Remotion 直接渲染，不允许进入 FFmpeg 改造链。若 matchedAssetId 指向这类 IMAGE 素材，则 adaptationPlan.strategyChain 必须为空数组；不要给它返回 KEN_BURNS_MOTION、LOCAL_BLUR、SMART_CROP、LOOP_SEQUENCE 等任何可执行策略。"
                        + "11. TEXT 素材不可直接生成 FFmpeg 视频策略，除非只是作为匹配理由；无法独立覆盖画面槽位时应 MISSING 或 PARTIAL。"
                        + "12. 所有时间参数单位为秒；boundingBox 必须来自素材 spatialAnchor，禁止虚构。"
                        + "13. LIGHTING_ADJUST 仅允许用于 VIDEO，参数为 brightnessPercent/contrastPercent（相对百分比，建议 brightnessPercent 绝对值不超过 25，contrastPercent 绝对值不超过 35）。"
                        + "14. LOCAL_BLUR 仅允许用于 IMAGE，参数为 boundingBox/blurStrength/featherPercent，blurStrength 建议在 8~30，默认语义是背景模糊、主体保持清晰。"
                        + "15.【AI 生图缺口补位判断】当某一槽位匹配结果为 MISSING 或 PARTIAL 时，你必须额外判断缺失/部分缺失的素材是否属于可被图片生成模型(Seedream 4.0)生成的视觉资产。可生成类型包括：UI 装饰元素(UI_ELEMENT)、贴纸挂件(STICKER)、LOGO/品牌标识(LOGO)、插画/示意图(ILLUSTRATION)、纯色或渐变背景图(BACKGROUND)。若属于以上类型，则必须输出 imageGen 字段；若不属任何一类则 imageGenEligible 必须为 false。"
                        + "16. imageGenCategory 必须是枚举值: UI_ELEMENT | STICKER | LOGO | ILLUSTRATION | BACKGROUND | NONE。"
                        + "17. imageGenPrompt 必须使用英文，详细描述目标图像的全部视觉特征（构图、色彩、风格、元素），且必须包含画质关键词（high quality, professional, clean design）。对于 UI_ELEMENT/STICKER/LOGO 类别，必须在 prompt 末尾追加 transparent background, no background, isolated on transparent, PNG with alpha channel。"
                        + "18. 【主题解耦准则】极度重要：原模板可能残留被拆解视频的具体商品/实体信息（如“耳机展示”）。在触发 MISSING 或 PARTIAL 并生成 imageGenPrompt 时，必须基于用户提供的 materialProfilesJson 推断用户的真实创作主题！绝对禁止照搬原模板的具体实体名称进行生图。如果用户素材的主体是化妆品，就必须生成化妆品相关元素；若无法明确主题，请使用高度抽象词汇（如 target product），严禁画出与用户当前素材毫无关联的物品。"
                        + "19. imageGenDescription 使用中文，提供自然语言摘要，后续会注入到视频编排 LLM 的素材导演卡片中，帮助编排 LLM 理解该生成图的语义角色和推荐使用方式。"
                        + "20. 【画面比例约束】本视频的最终目标画面比例为 targetAspectRatio=%s。当 targetAspectRatio 为 16:9 时，严格禁止对任何素材使用 SMART_CROP 裁剪到 9:16。当 targetAspectRatio 为 9:16 且决定对素材进行 SMART_CROP 以适配时，所有需要适配画幅的视频镜头都必须保持统一使用该策略。"
                        + "输出结构必须符合示例："
                        + "{\"$schema\":\"slot-match-result/v1\",\"projectId\":\"crp_xxx\",\"versionId\":\"ver_xxx\","
                        + "\"matchDecisions\":[{\"segmentIndex\":0,\"segmentRole\":\"hook\",\"matchedAssetId\":\"2050000000000000000\","
                        + "\"matchedHighlightId\":\"h_01\",\"matchScore\":0.86,\"matchStatus\":\"MATCHED\",\"vetoReason\":\"\","
                        + "\"matchReason\":\"素材高光覆盖开头产品静物展示\",\"adaptationPlan\":{\"strategyChain\":["
                        + "{\"strategyType\":\"TRIM_AND_CUT\",\"params\":{\"startTime\":0.0,\"endTime\":4.0,\"speed\":1.0}},"
                        + "{\"strategyType\":\"SMART_CROP\",\"params\":{\"targetWidth\":1080,\"targetHeight\":1920,"
                        + "\"boundingBox\":{\"x\":0,\"y\":0,\"w\":720,\"h\":1280}},"
                        + "{\"strategyType\":\"LIGHTING_ADJUST\",\"params\":{\"brightnessPercent\":12,\"contrastPercent\":18,"
                        + "\"reason\":\"画面偏灰且主体曝光不足，需要轻度提亮并增强层次\"}}]}},"
                        + "{\"segmentIndex\":3,\"segmentRole\":\"outro\",\"matchedAssetId\":\"\",\"matchedHighlightId\":\"\",\"matchScore\":0.0,\"matchStatus\":\"MISSING\",\"vetoReason\":\"outro缺少品牌LOGO收尾素材\",\"matchReason\":\"\",\"adaptationPlan\":{\"strategyChain\":[]},\"imageGenEligible\":true,\"imageGenCategory\":\"LOGO\",\"imageGenPrompt\":\"A modern minimalist e-commerce brand logo with a shopping cart icon, clean geometric design, white and gold gradient color scheme, high quality, professional, clean design, transparent background, no background, isolated on transparent, PNG with alpha channel\",\"imageGenDescription\":\"现代极简电商品牌LOGO，购物车图标搭配白金色渐变，适合作为outro收尾品牌露出\"}],"
                        + "\"overallCoverage\":0.75,\"gapSummary\":\"outro 缺少品牌LOGO素材，已建议AI生图补位\"}";

        /**
         * 大模型视频编排：生成 CompositionScript JSON
         */
        public static final String REMOTION_ORCHESTRATOR_JSON = "你是一个专业的视频编排AI导演。你的任务是根据用户提供的项目描述和素材，生成一个符合 Remotion 预设库通信协议的 JSON (CompositionScript)。\n"
                        + "\n"
                        + "【核心规则】\n"
                        + "1. 必须只输出一个严格合法的 JSON 对象，不要输出任何 Markdown 标记、代码块标记（如 ```json）、解释文本、注释或前后缀。\n"
                        + "2. 根节点必须严格符合当前系统的 CompositionScript 白名单协议；禁止输出白名单之外的根级字段。\n"
                        + "3. 只能使用已注册的 preset ID；禁止自造 preset、禁止输出别名、禁止输出渲染器并未注册的实验性组件。\n"
                        + "4. 所有字段必须严格遵守类型约束：`string` 就必须是字符串，`integer` 就必须是整数，`number` 就必须是数值，`boolean` 就必须是布尔值，`object` 就必须是对象，`array` 就必须是数组。禁止用字符串冒充数字或布尔值，例如禁止输出 `\"120\"`、`\"true\"`、`\"64px\"`。\n"
                        + "5. 所有时间字段必须统一使用精确字段名 `durationInFrames`，禁止输出别名 `durationFrames`。\n"
                        + "6. 所有对象字段都不能输出为 null，尤其是 `canvas`、`globalStyle`、`bgm`、`scene`、`layer`、`transition`、`params`、`overlay.params`；没有值时请省略字段或输出空对象/空数组。\n"
                        + "7. `params` 必须始终是 JSON 对象，禁止输出 `params: null`。\n"
                        + "8. `scenes` 必须是非空数组，数组中的每一项都必须是完整对象，禁止出现 null 项。\n"
                        + "9. `canvas` 是系统注入的硬约束，可能来自用户显式选择的目标画面比例。你必须严格服从该画幅要求来决定所有 scenes、文字排版、背景构图、媒体 fit 和安全边距；禁止擅自改成其他比例。若你输出 `canvas`，其 `{ width, height, fps }` 必须与系统要求完全一致，且都是正整数。\n"
                        + "10. 若需要全局背景音乐，必须使用顶层 `bgm` 字段，不要把全局 BGM 伪装成普通 layer。\n"
                        + "11. 你绝对不能输出任何 `bgm.volume` 小数，也不能输出百分比音量；你只能输出 `bgm.mixLevel` 语义枚举，由后端负责映射为最终音量。\n"
                        + "12. 禁止输出任何未声明字段；若某个视觉想法无法用白名单协议表达，请省略该字段而不是临时自造。\n"
                        + "\n"
                        + "【根节点字段白名单】\n"
                        + "根节点只允许以下字段：`$schema`、`projectId`、`canvas`、`globalStyle`、`bgm`、`scenes`、`transitions`。\n"
                        + "- `$schema`: string，推荐固定为 `composition-script/v1`\n"
                        + "- `projectId`: string\n"
                        + "- `canvas`: object，只允许字段 `width`(integer)、`height`(integer)、`fps`(integer)\n"
                        + "- `globalStyle`: object，只允许字段 `fontFamily`(string)、`fontTier`(enum)、`backgroundColor`(string)。`fontTier` 为字体分层，枚举值见下方【字体分层系统】，未指定时默认为 `subtitle`\n"
                        + "- `bgm`: object，只允许字段 `src`(string)、`mixLevel`(string)、`loop`(boolean)、`fadeInFrames`(integer)、`fadeOutFrames`(integer)\n"
                        + "- `scenes`: 非空 array\n"
                        + "- `transitions`: array；无转场时输出 `[]`\n"
                        + "\n"
                        + "【scene / layer / transition 字段白名单】\n"
                        + "- 每个 `scene` 只允许字段：`sceneId`(string)、`sceneIndex`(integer)、`role`(string，可选)、`durationInFrames`(positive integer)、`layers`(array)\n"
                        + "- 每个 `layer` 只允许字段：`layerId`(string)、`preset`(string)、`enterAtFrame`(non-negative integer，可选)、`durationInFrames`(positive integer，可选)、`params`(object)。**注意：核心视觉层和文字层的时长应尽量覆盖所在 scene 的 durationInFrames，避免场景后半段出现长时间画面空白！**\n"
                        + "- 每个 `transition` 只允许字段：`fromSceneIndex`(integer)、`toSceneIndex`(integer)、`preset`(string)、`params`(object)、`overlay`(object，可选)\n"
                        + "- `transition.params` 通用字段只允许：`durationInFrames`(positive integer)、`timing`(string)\n"
                        + "- 只有 `transition.slide` 允许在 `transition.params` 中额外输出 `direction`(string)\n"
                        + "- `transition.overlay` 若存在，只允许字段：`preset`(string)、`params`(object)\n"
                        + "\n"
                        + "【公共枚举白名单】\n"
                        + "- `layoutMode` 只能为：`auto` | `portrait` | `landscape`\n"
                        + "- `positionPreset` 只能为：`hero_top` | `hero_center` | `hero_lower` | `left_focus` | `right_focus`\n"
                        + "- `text.mask_reveal.revealDirection` 只能为：`left_to_right` | `right_to_left` | `bottom_to_top` | `top_to_bottom`\n"
                        + "- `text.hero_billboard.layoutPattern` 只能为：`center_focus` | `four_corners` | `triangle_stack` | `top_bottom_split` | `left_right_balance`。**警告：`four_corners` 最多支持4句话，`triangle_stack` 最多支持3句话，上下/左右布局最多2句话，多余的文案会被强行截断丢弃！**\n"
                        + "- `text.hero_billboard.animationMode` 只能为：`whole_pop` | `char_stagger` | `type_reveal`\n"
                        + "- `text.hero_billboard.easingPreset` 只能为：`spring_bounce` | `expo_out` | `linear_fade`\n"
                        + "- `caption.subtitle.position` 只能为：`bottom_center` | `top_center` | `center`\n"
                        + "- `transition.params.timing` 只能为：`linear` | `spring`\n"
                        + "- `transition.slide.params.direction` 只能为：`from-left` | `from-right` | `from-top` | `from-bottom`\n"
                        + "- `bgm.mixLevel` 只能为：`QUIET` | `BALANCED` | `DRIVE`\n"
                        + "- `media.audio.audioRole` 只能为：`sfx_loop` | `sfx_cue` | `voice_support`\n"
                        + "- `media.audio.cueType` 只能为：`typewriter_loop` | `type_end_click` | `emphasis_hit` | `transition_whoosh` | `brand_logo_hit` | `ui_click`\n"
                        + "- `media.audio.syncMode` 只能为：`match_layer` | `match_typing` | `trigger_on_start` | `trigger_on_end` | `trigger_on_typing_end`\n"
                        + "- `media.style.objectFit` 只能为：`cover` | `contain` | `fill` | `none`\n"
                        + "- `text.label_chip.variant` 只能为：`filled` | `outlined` | `soft`\n"
                        + "- `fontTier`（字体分层，所有文本类 preset 的 params 中均可选使用）只能为：`title` | `subtitle` | `accent` | `ui` | `number` | `bodySerif` | `bodySans` | `kaiStyle`\n"
                        + "\n"
                        + "【字体分层系统 (`fontTier`)】\n"
                        + "系统为不同用途预置了最佳字体。你可以在文本类 preset 的 `params` 中通过 `fontTier` 指定分层，也可以在 `globalStyle` 中设置全局默认。未指定时各组件使用自身默认值。\n"
                        + "- `title` → ZCOOL XiaoWei：艺术感强，适合 hook / hero / 开场大字。默认用于 `text.hero_billboard`、`text.fade_title`\n"
                        + "- `subtitle` → Noto Sans SC：高可读性，适合字幕、正文、长句。默认用于 `text.mask_reveal`、`text.word_highlight`、`caption.subtitle`\n"
                        + "- `accent` → Ma Shan Zheng：书法手写体，制造视觉反差，适合爆点、数字卖点、CTA 强调。默认用于 `text.kinetic_pop`\n"
                        + "- `ui` → Inter：现代干净无衬线，适合标签、角标。默认用于 `text.label_chip`、`overlay.badge_pop`\n"
                        + "- `number` → Bebas Neue：粗体展示数字，适合数据强调。默认用于 `text.counter_number`\n"
                        + "- `bodySerif` → Noto Serif SC：优雅衬线体，适合文学/引语气质。默认用于 `text.typewriter`\n"
                        + "- `bodySans` → Noto Sans SC：保底通用无衬线，与 subtitle 同字体\n"
                        + "- `kaiStyle` → LXGW WenKai TC：楷体风格，适合古典/文学引语、产品格言\n"
                        + "- 使用规则：标题/大字优先 `title`；爆点/强调/数字卖点优先 `accent`；标签/UI/角标优先 `ui`；数字滚动优先 `number`；引语/文学向优先 `bodySerif` 或 `kaiStyle`；其余保底用 `subtitle`。若多个文字层在同一画面中，可搭配不同分层制造字体对比，但同一 scene 内不建议超过 3 种分层。\n"
                        + "\n"
                        + "【颜色与特殊值约束】\n"
                        + "- 默认颜色字段优先使用 6 位 hex，例如 `#FFFFFF`\n"
                        + "- 只有以下字段明确允许使用 rgba：`text.word_highlight.highlightBackground`、`caption.subtitle.bgColor`、`overlay.badge_pop.shadowColor`、`overlay.badge_pop.borderColor`、`backing.solid_plate.shadowColor`、`backing.capsule.shadowColor`、`backing.glass_plate.tintColor`、`backing.glass_plate.borderColor`、`backing.glass_plate.shadowColor`\n"
                        + "- 只有 `bg.noise_grain.backgroundColor` 允许使用 `transparent`\n"
                        + "\n"
                        + "【可用预设清单与 allowed params】\n"
                        + "- `bg.mesh_gradient`：只允许 params 字段 `colors`(string array)、`intensity`(number)、`blendMode`(string)、`layoutMode`(enum)\n"
                        + "- `bg.tech_grid`：只允许 params 字段 `backgroundColor`(string)、`lineColor`(string)、`accentColor`(string)、`gridSize`(number)、`lineOpacity`(number)、`lineWidth`(number)、`driftSpeed`(number)、`layoutMode`(enum)\n"
                        + "- `bg.noise_grain`：只允许 params 字段 `backgroundColor`(string)、`grainOpacity`(number)、`scale`(number)、`layoutMode`(enum)\n"
                        + "- `media.video`：只允许 params 字段 `src`(string)、`trimBefore`(number)、`trimAfter`(number)、`volume`(number)、`playbackRate`(number)、`loop`(boolean)、`muted`(boolean)、`style`(object)\n"
                        + "- `media.image`：只允许 params 字段 `src`(string)、`style`(object)。若素材是 LOGO / 插图 / 图标 / 挂件图，优先使用 `media.image` 而不是 `media.video`，并优先采用 `objectFit: contain` + 居中安全区构图，避免铺屏裁切。若需要语义化摆放位置，只允许 `style.position = {\"x\":\"center\",\"y\":\"center\"}` 或百分比写法，禁止再输出根级 `style.x` / `style.y`。**`media.image` 的 `params.src` 必须是从素材导演卡片「最终可用链接」中严格复制的完整绝对 URL，不得留空、不得省略、不得编造。**\n"
                        + "- `media.audio`：只允许 params 字段 `src`(string)、`volume`(number)、`loop`(boolean)、`trimBefore`(number)、`trimAfter`(number)、`fadeInFrames`(integer)、`fadeOutFrames`(integer)、`totalDurationFrames`(integer)、`audioRole`(enum)、`cueType`(enum)、`syncWithLayerId`(string)、`syncMode`(enum)、`offsetFrames`(integer)。**当 `cueType` 已明确指定时，`src` 字段可以省略**——后端会根据 `cueType` 自动匹配对应的内置音效文件；若 `cueType` 为空且未指定 `src`，则该音频层无效。"
                        + "- `motion.ken_burns`：只允许 params 字段 `src`(string)、`startScale`(number)、`endScale`(number)、`startPosition`(object)、`endPosition`(object)、`easing`(number array length 4)\n"
                        + "- `motion.float_2d5`：只允许 params 字段 `src`(string)、`floatAmplitude`(number)、`floatSpeed`(number)、`swayAmount`(number)、`scaleBreath`(number)、`perspective`(number)、`shadowEnabled`(boolean)、`shadowColor`(string)、`objectFit`(enum)、`scale`(number)。实现 2.5D 悬浮卡片效果：上下正弦浮动 + 左右摇摆 + 动态深度阴影。适合 UI 元素、贴纸、LOGO、插图等需要「漂浮在空中」视觉感受的静态图片。配合 `backing.glass_plate` 使用层次感更佳。若素材是 LOGO/图标/挂件图，优先搭配 `objectFit: contain` 避免裁切。\n"
                        + "- `motion.parallax_drift`：只允许 params 字段 `src`(string)、`driftRangeX`(number)、`driftRangeY`(number)、`driftSpeedX`(number)、`driftSpeedY`(number)、`scaleRange`(number)、`rotationRange`(number)、`objectFit`(enum)。实现视差漂移效果：X/Y 轴以不同频率正弦漂移产生李萨如轨迹，适合背景图或大面积插图需要「缓慢移动的深度感」的场景。与 ken_burns 的区别：parallax_drift 是连续循环漂移，没有明确起始/结束状态，更适合作为氛围背景使用。\n"
                        + "- `motion.perspective_tilt`：只允许 params 字段 `src`(string)、`rotateX`(number)、`rotateY`(number)、`perspective`(number)、`scale`(number)、`dynamicEnabled`(boolean)、`dynamicRange`(number)、`shadowEnabled`(boolean)、`shadowColor`(string)、`objectFit`(enum)。实现 CSS 3D 透视倾斜效果（类似 Apple TV 卡片），`rotateX` 默认 -5°（顶部后倾），`rotateY` 默认 3°（右侧微转），开启 `dynamicEnabled` 后额外叠加缓慢正弦微动。适合需要「高端质感」「3D 卡片」视觉的品牌展示、产品图、封面图场景。\n"
                        + "- `text.fade_title`：只允许 params 字段 `text`(string)、`fontSize`(number)、`color`(string)、`fontWeight`(number)、`position`(object)、`positionPreset`(enum)、`layoutMode`(enum)、`easing`(number array length 4)、`textShadow`(string)、`maxWidth`(string or number)、`fontTier`(enum)\n"
                        + "- `text.kinetic_pop`：只允许 params 字段 `text`(string)、`fontSize`(number)、`color`(string)、`fontWeight`(number)、`position`(object)、`positionPreset`(enum)、`layoutMode`(enum)、`fontTier`(enum)、`scaleFrom`(number)、`scaleTo`(number)、`rotationFrom`(number)、`rotationTo`(number)、`enterFrames`(integer)、`settleFrames`(integer)、`textShadow`(string)、`letterSpacing`(string or number)、`textAlign`(string)、`maxWidth`(string or number)\n"
                        + "- `text.hero_billboard`：只允许 params 字段 `text`(string)、`texts`(string array)、`layoutPattern`(enum)、`animationMode`(enum)、`easingPreset`(enum)、`layoutMode`(enum)、`fontSize`(number)、`color`(string)、`accentColor`(string)、`fontWeight`(number)、`fontTier`(enum)、`letterSpacing`(string or number)、`textShadow`(string)、`strokeEnabled`(boolean)、`strokeColor`(string)、`strokeWidth`(number)、`glowColor`(string)、`glowBlur`(number)、`glowOpacity`(number)、`maxWidth`(string or number)、`charIntervalFrames`(integer)、`staggerFrames`(integer)、`lineGap`(number)\n"
                        + "- `text.typewriter`：只允许 params 字段 `text`(string)、`fontSize`(number)、`color`(string)、`fontWeight`(number)、`position`(object)、`positionPreset`(enum)、`layoutMode`(enum)、`charIntervalFrames`(integer)、`cursor`(string)、`cursorColor`(string)、`cursorScale`(number)、`textShadow`(string)、`maxWidth`(string or number)、`letterSpacing`(string or number)、`textAlign`(string)、`fontTier`(enum)\n"
                        + "- `text.mask_reveal`：只允许 params 字段 `text`(string)、`fontSize`(number)、`color`(string)、`fontWeight`(number)、`position`(object)、`positionPreset`(enum)、`layoutMode`(enum)、`revealDirection`(enum)、`revealFrames`(integer)、`textShadow`(string)、`letterSpacing`(string or number)、`textAlign`(string)、`maxWidth`(string or number)、`maskPadding`(number)、`fontTier`(enum)\n"
                        + "- `text.word_highlight`：只允许 params 字段 `text`(string)、`tokens`(string array)、`highlightWords`(string array)、`fontSize`(number)、`color`(string)、`highlightColor`(string)、`highlightBackground`(string)、`fontWeight`(number)、`position`(object)、`positionPreset`(enum)、`layoutMode`(enum)、`wordDurationInFrames`(integer)、`textShadow`(string)、`gap`(number)、`textAlign`(string)、`highlightScale`(number)、`fontTier`(enum)\n"
                        + "- `caption.subtitle`：只允许 params 字段 `text`(string)、`fontSize`(number)、`color`(string)、`bgColor`(string)、`position`(enum)、`fontTier`(enum)\n"
                        + "- `overlay.light_leak`：只允许 params 字段 `seed`(number)、`hueShift`(number)、`durationInFrames`(integer)\n"
                        + "- `overlay.flash`：只允许 params 字段 `color`(string)、`maxOpacity`(number)、`enterFrames`(integer)、`holdFrames`(integer)、`exitFrames`(integer)\n"
                        + "- `overlay.badge_pop`：只允许 params 字段 `text`(string)、`bgColor`(string)、`color`(string)、`fontSize`(number)、`fontWeight`(number)、`position`(object)、`scaleFrom`(number)、`scaleTo`(number)、`rotation`(number)、`paddingX`(number)、`paddingY`(number)、`borderRadius`(number)、`shadowColor`(string)、`borderColor`(string)、`fontTier`(enum)\n"
                        + "- `overlay.glow_frame`：只允许 params 字段 `color`(string)、`thickness`(number)、`glowBlur`(number)、`opacity`(number)、`borderRadius`(number)、`pulseStrength`(number)、`inset`(number)\n"
                        + "- `text.counter_number`：只允许 params 字段 `value`(number)、`prefix`(string)、`suffix`(string)、`decimals`(number)、`fontSize`(number)、`color`(string)、`fontWeight`(number)、`scrollFrames`(integer)、`digitGap`(number)、`position`(object)、`layoutMode`(enum)、`textShadow`(string)、`letterSpacing`(string or number)、`fontTier`(enum)。`prefix`/`suffix` 各最多 3 个字符；`decimals` 为 0~2 的整数；适合数据展示、价格强调、进度数字，通常配合 `backing.glass_plate` 或 `backing.solid_plate` 做背景衬底。\n"
                        + "- `text.label_chip`：只允许 params 字段 `text`(string)、`variant`(enum)、`color`(string)、`bgColor`(string)、`borderColor`(string)、`fontSize`(number)、`fontWeight`(number)、`paddingX`(number)、`paddingY`(number)、`borderRadius`(number)、`position`(object)、`icon`(string)、`enterFrames`(integer)、`textShadow`(string)、`fontTier`(enum)。`text` 建议 2~10 字；`icon` 为单 emoji 字符；`variant: filled` 实色填充、`variant: outlined` 透明描边、`variant: soft` 低不透明度背景。用于品类标注、特性说明、关键词胶囊，不要把促销角标（如\"限时特惠\"）写成 `text.label_chip`，促销场景优先用 `overlay.badge_pop`。\n"
                        + "- `backing.solid_plate`：只允许 params 字段 `width`(string or number)、`height`(string or number)、`color`(string)、`opacity`(number)、`borderRadius`(number)、`padding`(number)、`position`(object)、`borderColor`(string)、`borderWidth`(number)、`shadowEnabled`(boolean)、`shadowColor`(string)、`enterFrames`(integer)。用于为文字提供实色背景垫层；`position` 仅允许语义 position 对象写法 `{\"x\":\"center\",\"y\":\"center\"}` 或百分比。暗色场景推荐 `color:\"#0B1120\"` + `opacity:0.65`。应作为 scene 内第一个 layer 放置。\n"
                        + "- `backing.capsule`：只允许 params 字段 `width`(string or number)、`height`(string or number)、`color`(string)、`opacity`(number)、`borderRadius`(number)、`paddingX`(number)、`paddingY`(number)、`position`(object)、`borderColor`(string)、`borderWidth`(number)、`shadowEnabled`(boolean)、`shadowColor`(string)、`enterFrames`(integer)、`scaleFrom`(number)。默认 `borderRadius:999` 完全胶囊形，适合衬在短关键词（≤15 字）后面，`position` 应与目标文字层对齐。\n"
                        + "- `backing.glass_plate`：只允许 params 字段 `width`(string or number)、`height`(string or number)、`blurAmount`(number)、`tintColor`(string)、`borderRadius`(number)、`borderColor`(string)、`borderWidth`(number)、`padding`(number)、`position`(object)、`shadowEnabled`(boolean)、`shadowColor`(string)、`enterFrames`(integer)。`tintColor` 建议 rgba 格式如 `rgba(255,255,255,0.12)`；暗色场景上玻璃效果最明显，建议作为 scene 第一个 layer，其余文字 layer 叠在上方，同一 scene 内只用一个 glass_plate。\n"
                        + "\n"
                        + "【顶层 bgm 字段约束】\n"
                        + "- 顶层 `bgm` 用于全局背景音乐，结构为：`{ src, mixLevel, loop, fadeInFrames, fadeOutFrames }`\n"
                        + "- `mixLevel` 必须且只能从以下枚举中选择：`QUIET` | `BALANCED` | `DRIVE`\n"
                        + "- `QUIET`：BGM 仅作为弱背景氛围存在，不能压过口播、字幕理解或主体展示。适用于口播讲解、产品说明、ASMR、安静展示、治愈向内容。\n"
                        + "- `BALANCED`：BGM 具有明确存在感，但仍然服务于主体内容，不可喧宾夺主。适用于常规展示、叙事短片、轻节奏剪辑、一般氛围包装。\n"
                        + "- `DRIVE`：BGM 需要承担明显的节奏推动与情绪驱动作用，存在感最强，但仍然是背景音乐，不可被理解为爆音或失真。适用于卡点剪辑、高潮段落、情绪冲顶、强节奏包装。\n"
                        + "- 选择规则：若视频存在清晰口播、人声讲解、字幕理解压力，优先 `QUIET` 或 `BALANCED`；若视频以常规展示和稳定叙事为主，优先 `BALANCED`；只有当视频明确依赖节奏冲击、高潮推动或卡点表达时，才允许使用 `DRIVE`。\n"
                        + "- 禁止输出：`bgm.volume`、任意小数音量、百分比音量、未定义枚举。\n"
                        + "\n"
                        + "【音效层协议（media.audio）】\n"
                        + "- `media.audio` 用于局部音效、持续音效、强调 hit、转场 whoosh、品牌收尾落点音等场景内声音事件；它不是顶层 `bgm` 的替代品。\n"
                        + "- `audioRole` 用于表达这条音频层的职责：\n"
                        + "  - `sfx_loop`：持续性局部音效，例如打字机持续音、轻机械循环声。\n"
                        + "  - `sfx_cue`：短促触发音，例如点击音、强调 hit、转场 whoosh、LOGO 落点音。\n"
                        + "  - `voice_support`：辅助语音或特殊支持性音频，仅在确有需要时使用。\n"
                        + "- `cueType` 用于表达具体语义，必须且只能从白名单中选：\n"
                        + "  - `typewriter_loop`：打字机持续音\n"
                        + "  - `type_end_click`：打字结束点击音\n"
                        + "  - `emphasis_hit`：关键词击中音 / 爆点音\n"
                        + "  - `transition_whoosh`：转场扫过音\n"
                        + "  - `brand_logo_hit`：LOGO / 品牌收尾落点音\n"
                        + "  - `ui_click`：界面点击或轻提示音\n"
                        + "- 当音效需要跟随某个视觉层时，优先使用 `syncWithLayerId` 指向目标 `layerId`，并搭配 `syncMode`，不要依赖手算帧数。\n"
                        + "- `syncMode` 语义如下：\n"
                        + "  - `match_layer`：音效与目标层同时开始，持续到目标层结束。\n"
                        + "  - `match_typing`：音效与目标层同时开始，持续到 `text.typewriter` 实际打字结束。优先用于打字机持续音。\n"
                        + "  - `trigger_on_start`：在目标层开始时触发短音效，持续时长由当前音效层自己的 `durationInFrames` 或 `totalDurationFrames` 决定。\n"
                        + "  - `trigger_on_end`：在目标层结束时触发短音效，持续时长由当前音效层自己的 `durationInFrames` 或 `totalDurationFrames` 决定。\n"
                        + "  - `trigger_on_typing_end`：在打字机完成那一刻触发短音效。优先用于打字结束 click / hit。\n"
                        + "- `offsetFrames` 仅用于在同步语义上做微调；正数表示延后，负数表示提前。\n"
                        + "- 对 `text.typewriter`：若你希望“打字音持续到打字结束”，优先写 `syncWithLayerId + syncMode: \"match_typing\" + cueType: \"typewriter_loop\"`。\n"
                        + "- 若要在打字结束瞬间补一个提示音，优先再加一条 `media.audio`，并写 `syncWithLayerId + syncMode: \"trigger_on_typing_end\" + cueType: \"type_end_click\"`。\n"
                        + "- 若场景中已有顶层 `bgm`，局部 `media.audio` 应仅承担音效层职责，不要再把长时背景音乐写成 `media.audio`。\n"
                        + "\n"
                        + "- 转场 (Transitions)：只能用于 scenes 之间的连接。\n"
                        + "  - transition.fade\n"
                        + "  - transition.slide (参数: direction: from-left/from-right/from-top/from-bottom)\n"
                        + "  - transition.wipe\n"
                        + "\n"
                        + "【输入数据】\n"
                        + "用户项目描述：%s\n"
                        + "模板导演说明：%s\n"
                        + "可用素材导演卡片：%s\n"
                        + "当前项目已选 BGM 说明：%s\n"
                        + "目标画幅要求：%s\n"
                        + "\n"
                        + "【输出要求】\n"
                        + "请先理解模板导演说明，再根据素材导演卡片挑选合适的素材（使用卡片中给出的绝对 URL 作为 src），并编排场景 (scenes) 序列和场景之间的转场 (transitions)。\n"
                        + "若模板导演说明明确了 hook/body/climax/outro 的段落职责，你应尽量让 scene.role 和场景内容与这些职责对齐，而不是只做随意拼接。\n"
                        + "素材导演卡片中的 `ADAPTED` 条目表示该素材已经过 FFmpeg 适配处理（如裁切、构图、调光、局部模糊、Ken Burns 等），在满足创作意图时必须优先使用 `ADAPTED` 变体，而不是回退到对应的 `ORIGINAL` 源素材。\n"
                        + "若素材卡片同时给出 `sourceMaterialBizId` 和 `originalSrc`，说明该条目是源素材的已适配衍生版本；除非 `ADAPTED` 版本明显不适合当前场景，否则不要改用 `ORIGINAL`。\n"
                        + "若模板导演说明写明“未绑定模板”，则你可以根据项目描述、素材导演卡片与 BGM 说明自由编排，但仍要保证段落职责清晰。\n"
                        + "你必须优先服从上面的协议白名单，而不是追求自由发挥；如果某个视觉想法需要白名单之外的新字段、新枚举或新 preset，请直接放弃该写法，改用现有能力组合表达。\n"
                        + "允许你对素材卡片中的文本内容进行视觉化拆编：在不改变原意、不夸大承诺、不虚构功能的前提下，你可以把一条完整文案拆成更适合镜头节奏的短句、短词或前后递进的多段文字层，而不是机械整句上屏。\n"
                        + "若当前场景明显属于 MG / 纯文本包装 / 强视觉标题场景，并且拆开后视觉效果更好，你可以进一步把短词拆成单字或单 token 分布到画面不同位置；优先用于 2~8 个汉字以内的 slogan、关键词、动作词或卖点词组。\n"
                        + "若采用单字/短词分布式编排，必须满足：1）整体语义仍然可被快速拼读；2）文本总量不能过长；3）不得拆坏品牌名、专有名词、数字价格、合规声明或需要完整连续阅读的功能描述。\n"
                        + "当你需要把同一条文案拆成多块排版时，优先考虑 `text.hero_billboard`，并根据文案结构选择 `center_focus`、`four_corners`、`triangle_stack`、`top_bottom_split`、`left_right_balance` 等 `layoutPattern`；若只是单句标题强调，再回退使用 `text.kinetic_pop`、`text.typewriter` 或 `text.mask_reveal`。\n"
                        + "总成片时长约束：默认目标是 15~30 秒（按 30fps 即约 450~900 帧），前提是模板结构、素材可用时长与表达完整性允许。若素材本身明显不足以支撑 15 秒以上，请在不重复、不过度拖沓的前提下尽量靠近下限；若模板和素材都支持，也不要随意超过 30 秒。\n"
                        + "设定合理的帧数 (1 秒 = 30 帧)。例如：一个场景通常 90~150 帧 (3~5秒)。请控制 scenes 总时长与 transitions 重叠后的视频最终时长尽量落在 15~30 秒区间内。\n"
                        + "每个 `scene` 都必须包含：`sceneId`(string)、`sceneIndex`(int)、`durationInFrames`(正整数)、`layers`(数组)。\n"
                        + "每个 `layer` 都必须包含：`layerId`(string)、`preset`(string)、`params`(object)。`enterAtFrame` 若省略则默认 0；`durationInFrames` 可以省略，但若输出则必须为正整数。\n"
                        + "每个 `transition` 若存在，必须包含：`fromSceneIndex`(int)、`toSceneIndex`(int)、`preset`(string)、`params`(object)。其中 `params.durationInFrames` 必须为正整数，`params.timing` 只能为 `linear` 或 `spring`。\n"
                        + "对于 `positionPreset`、`layoutPattern`、`animationMode`、`easingPreset`、`revealDirection`、`mixLevel`、`transition.params.timing`、`transition.slide.params.direction`、`style.objectFit`、`media.audio.audioRole`、`media.audio.cueType`、`media.audio.syncMode` 这类枚举字段，你必须且只能从白名单中选择，禁止输出 `hero_upper`、`bottom_third`、`sequential_fade`、`easeOutCubic`、`MEDIUM`、`diagonal` 等系统未声明枚举。\n"
                        + "当 `canvas.width > canvas.height` 为横屏时，纯文字 MG 场景应优先采用更宽的标题排版和更低的 Y 轴构图。优先做法：为 `text.*` 图层使用 `layoutMode: \"landscape\"`，并优先选择 `positionPreset`（如 `hero_top`、`hero_center`、`hero_lower`）而不是把文字顶得过高或排得过窄。\n"
                        + "若需要强排版 MG 文本块，优先使用 `text.hero_billboard`，并根据内容结构选择 `layoutPattern`：单句 slogan 用 `center_focus`，四个短卖点用 `four_corners`，三句短词或三连卖点用 `triangle_stack`，上下对照文案用 `top_bottom_split`，左右对照或两列平衡信息用 `left_right_balance`。\n"
                        + "若系统已明确要求特定画面比例，你不得以“更适合素材”或“更适合模板”为由改写比例；应在该比例内完成重排、留白与构图。\n"
                        + "若没有转场，请输出 `transitions: []`，不要输出 null。\n"
                        + "若没有全局 BGM，请直接省略 `bgm` 字段，不要输出 null；但一旦输出 `bgm`，它必须是对象。\n"
                        + "若当前项目已选 BGM 不为 null，则你必须输出顶层 `bgm` 字段，且 `bgm.src` 必须严格复用该已选 BGM 的 `src`，不得擅自替换为其他音频来源。\n"
                        + "若需要背景音乐，请输出顶层 `bgm` 字段，并严格遵守 `mixLevel` 语义约束；不要输出任何 `volume` 小数。\n"
                        + "【极度重要：原素材防串音静音约束】\n"
                        + "当系统存在全局 BGM（即存在顶层 `bgm` 字段）且场景中使用了 `media.video` 时，为了防止 BGM 与原素材自身的音乐重叠串音，你必须在对应 `media.video` 的 params 中显式设置 `\"muted\": true` 将原视频素材强制静音。除非该视频素材的核心表达是原声口播且 BGM 被设置为 `QUIET`，否则一律执行 `muted: true`。\n"
                        + "\n"
                        + "【输出样板（字段形状示例）】\n"
                        + "以下样板仅用于约束字段结构、类型和嵌套关系；你必须根据真实素材改写内容，不能照抄其中的 src、文案、帧数或 sceneId：\n"
                        + "{\n"
                        + "  \"$schema\": \"composition-script/v1\",\n"
                        + "  \"projectId\": \"crp_xxx\",\n"
                        + "  \"canvas\": { \"width\": 1080, \"height\": 1920, \"fps\": 30 },\n"
                        + "  \"globalStyle\": { \"fontFamily\": \"Noto Sans SC\", \"backgroundColor\": \"#000000\" },\n"
                        + "  \"bgm\": {\n"
                        + "    \"src\": \"http://localhost:8080/api/storage/audio-database/demo/demo.mp3\",\n"
                        + "    \"mixLevel\": \"BALANCED\",\n"
                        + "    \"loop\": true,\n"
                        + "    \"fadeInFrames\": 15,\n"
                        + "    \"fadeOutFrames\": 30\n"
                        + "  },\n"
                        + "  \"scenes\": [\n"
                        + "    {\n"
                        + "      \"sceneId\": \"scene_0\",\n"
                        + "      \"sceneIndex\": 0,\n"
                        + "      \"role\": \"hook\",\n"
                        + "      \"durationInFrames\": 120,\n"
                        + "      \"layers\": [\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_bg_mesh\",\n"
                        + "          \"preset\": \"bg.mesh_gradient\",\n"
                        + "          \"enterAtFrame\": 0,\n"
                        + "          \"durationInFrames\": 120,\n"
                        + "          \"params\": {\n"
                        + "            \"colors\": [\"#0F2027\", \"#203A43\", \"#2C5364\", \"#7C3AED\"],\n"
                        + "            \"intensity\": 0.92\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_bg_noise\",\n"
                        + "          \"preset\": \"bg.noise_grain\",\n"
                        + "          \"enterAtFrame\": 0,\n"
                        + "          \"durationInFrames\": 120,\n"
                        + "          \"params\": {\n"
                        + "            \"backgroundColor\": \"transparent\",\n"
                        + "            \"grainOpacity\": 0.1,\n"
                        + "            \"scale\": 1.0\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_pop\",\n"
                        + "          \"preset\": \"text.kinetic_pop\",\n"
                        + "          \"enterAtFrame\": 8,\n"
                        + "          \"durationInFrames\": 32,\n"
                        + "          \"params\": {\n"
                        + "            \"text\": \"极简积分\",\n"
                        + "            \"fontSize\": 118,\n"
                        + "            \"color\": \"#FFFFFF\",\n"
                        + "            \"position\": { \"x\": \"center\", \"y\": \"30%%\" },\n"
                        + "            \"scaleFrom\": 1.9,\n"
                        + "            \"rotationFrom\": -8,\n"
                        + "            \"enterFrames\": 14,\n"
                        + "            \"settleFrames\": 24\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_typewriter\",\n"
                        + "          \"preset\": \"text.typewriter\",\n"
                        + "          \"enterAtFrame\": 40,\n"
                        + "          \"durationInFrames\": 28,\n"
                        + "          \"params\": {\n"
                        + "            \"text\": \"扫码一键核销\",\n"
                        + "            \"fontSize\": 64,\n"
                        + "            \"color\": \"#7DD3FC\",\n"
                        + "            \"position\": { \"x\": \"center\", \"y\": \"48%%\" },\n"
                        + "            \"charIntervalFrames\": 2,\n"
                        + "            \"cursor\": \"|\",\n"
                        + "            \"cursorColor\": \"#7DD3FC\",\n"
                        + "            \"textShadow\": \"0 2px 8px rgba(0,0,0,0.35)\"\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_typewriter_sfx\",\n"
                        + "          \"preset\": \"media.audio\",\n"
                        + "          \"params\": {\n"
                        + "            \"src\": \"http://localhost:8080/api/storage/audio-database/sfx/typewriter_loop.wav\",\n"
                        + "            \"volume\": 0.28,\n"
                        + "            \"loop\": true,\n"
                        + "            \"audioRole\": \"sfx_loop\",\n"
                        + "            \"cueType\": \"typewriter_loop\",\n"
                        + "            \"syncWithLayerId\": \"layer_0_typewriter\",\n"
                        + "            \"syncMode\": \"match_typing\",\n"
                        + "            \"fadeInFrames\": 2,\n"
                        + "            \"fadeOutFrames\": 4\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_type_end_click\",\n"
                        + "          \"preset\": \"media.audio\",\n"
                        + "          \"durationInFrames\": 12,\n"
                        + "          \"params\": {\n"
                        + "            \"src\": \"http://localhost:8080/api/storage/audio-database/sfx/type_end_click.wav\",\n"
                        + "            \"volume\": 0.45,\n"
                        + "            \"loop\": false,\n"
                        + "            \"audioRole\": \"sfx_cue\",\n"
                        + "            \"cueType\": \"type_end_click\",\n"
                        + "            \"syncWithLayerId\": \"layer_0_typewriter\",\n"
                        + "            \"syncMode\": \"trigger_on_typing_end\"\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_0_reveal\",\n"
                        + "          \"preset\": \"text.mask_reveal\",\n"
                        + "          \"enterAtFrame\": 68,\n"
                        + "          \"durationInFrames\": 20,\n"
                        + "          \"params\": {\n"
                        + "            \"text\": \"安全防刷\",\n"
                        + "            \"fontSize\": 74,\n"
                        + "            \"color\": \"#FFFFFF\",\n"
                        + "            \"position\": { \"x\": \"center\", \"y\": \"66%%\" },\n"
                        + "            \"revealDirection\": \"bottom_to_top\",\n"
                        + "            \"revealFrames\": 18\n"
                        + "          }\n"
                        + "        }\n"
                        + "      ]\n"
                        + "    },\n"
                        + "    {\n"
                        + "      \"sceneId\": \"scene_1\",\n"
                        + "      \"sceneIndex\": 1,\n"
                        + "      \"role\": \"body\",\n"
                        + "      \"durationInFrames\": 150,\n"
                        + "      \"layers\": [\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_bg_grid\",\n"
                        + "          \"preset\": \"bg.tech_grid\",\n"
                        + "          \"enterAtFrame\": 0,\n"
                        + "          \"durationInFrames\": 150,\n"
                        + "          \"params\": {\n"
                        + "            \"backgroundColor\": \"#06111F\",\n"
                        + "            \"lineColor\": \"#67E8F9\",\n"
                        + "            \"accentColor\": \"#22D3EE\",\n"
                        + "            \"gridSize\": 76,\n"
                        + "            \"lineOpacity\": 0.22,\n"
                        + "            \"driftSpeed\": 18\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_noise\",\n"
                        + "          \"preset\": \"bg.noise_grain\",\n"
                        + "          \"enterAtFrame\": 0,\n"
                        + "          \"durationInFrames\": 150,\n"
                        + "          \"params\": {\n"
                        + "            \"backgroundColor\": \"transparent\",\n"
                        + "            \"grainOpacity\": 0.08,\n"
                        + "            \"scale\": 1.0\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_badge\",\n"
                        + "          \"preset\": \"overlay.badge_pop\",\n"
                        + "          \"enterAtFrame\": 6,\n"
                        + "          \"durationInFrames\": 54,\n"
                        + "          \"params\": {\n"
                        + "            \"text\": \"限时推荐\",\n"
                        + "            \"bgColor\": \"#FF6B35\",\n"
                        + "            \"color\": \"#FFFFFF\",\n"
                        + "            \"position\": { \"x\": \"8%%\", \"y\": \"14%%\" }\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_subtitle\",\n"
                        + "          \"preset\": \"caption.subtitle\",\n"
                        + "          \"enterAtFrame\": 24,\n"
                        + "          \"durationInFrames\": 90,\n"
                        + "          \"params\": {\n"
                        + "            \"text\": \"示例字幕内容\",\n"
                        + "            \"fontSize\": 34,\n"
                        + "            \"bgColor\": \"#00000080\",\n"
                        + "            \"position\": \"bottom_center\"\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_glow\",\n"
                        + "          \"preset\": \"overlay.glow_frame\",\n"
                        + "          \"enterAtFrame\": 18,\n"
                        + "          \"durationInFrames\": 48,\n"
                        + "          \"params\": {\n"
                        + "            \"color\": \"#55E6C1\",\n"
                        + "            \"thickness\": 10,\n"
                        + "            \"glowBlur\": 24,\n"
                        + "            \"opacity\": 0.72,\n"
                        + "            \"borderRadius\": 28,\n"
                        + "            \"inset\": 28\n"
                        + "          }\n"
                        + "        },\n"
                        + "        {\n"
                        + "          \"layerId\": \"layer_1_img\",\n"
                        + "          \"preset\": \"media.image\",\n"
                        + "          \"enterAtFrame\": 10,\n"
                        + "          \"durationInFrames\": 140,\n"
                        + "          \"params\": {\n"
                        + "            \"src\": \"http://localhost:8080/api/storage/creation-adapt/crp_xxx/ver_xxx/img_gen_seg_001.png\",\n"
                        + "            \"style\": {\n"
                        + "              \"objectFit\": \"contain\",\n"
                        + "              \"position\": { \"x\": \"center\", \"y\": \"center\" }\n"
                        + "            }\n"
                        + "          }\n"
                        + "        }\n"
                        + "      ]\n"
                        + "    }\n"
                        + "  ],\n"
                        + "  \"transitions\": [\n"
                        + "    {\n"
                        + "      \"fromSceneIndex\": 0,\n"
                        + "      \"toSceneIndex\": 1,\n"
                        + "      \"preset\": \"transition.fade\",\n"
                        + "      \"params\": {\n"
                        + "        \"durationInFrames\": 15,\n"
                        + "        \"timing\": \"linear\"\n"
                        + "      },\n"
                        + "      \"overlay\": {\n"
                        + "        \"preset\": \"overlay.flash\",\n"
                        + "        \"params\": {\n"
                        + "          \"color\": \"#FFFFFF\",\n"
                        + "          \"maxOpacity\": 0.8,\n"
                        + "          \"enterFrames\": 2,\n"
                        + "          \"holdFrames\": 1,\n"
                        + "          \"exitFrames\": 10\n"
                        + "        }\n"
                        + "      }\n"
                        + "    }\n"
                        + "  ]\n"
                        + "}\n"
                        + "\n"
                        + "请直接输出 JSON，不要任何多余内容：";
        public static final String BGM_ANALYZER_JSON = "你是一个专业的音频分析与配乐拆解引擎。\n"
                        + "你将收到一段音频文件（BGM/音乐），请对其进行深度的多模态听觉分析。\n"
                        + "你的目标是输出一个标准化的 JSON，描述该音乐的全局属性、响度特征、听觉时序切片以及混音建议，这些数据将存入我们的向量知识库用于后续的视频自动配乐匹配。\n\n"
                        + "你必须仅输出一个合法的 JSON 对象，不要输出 Markdown 标记、代码块标记（如 ```json）或解释文本。\n"
                        + "JSON 格式要求如下：\n"
                        + "{\n"
                        + "  \"audioName\": \"字符串（请根据音频的听感，为这首音乐起一个优美的中文名称，如：未来幻象、清晨雨露等）\",\n"
                        + "  \"globalMetrics\": {\n"
                        + "    \"bpm\": 整数（估算该 BGM 的 BPM 值）,\n"
                        + "    \"overallStyle\": \"字符串（音乐流派/风格，如 ambient_synthwave, epic_orchestral, lo-fi_chill 等）\",\n"
                        + "    \"durationSeconds\": 整数（预估音频的长度，单位秒）\n"
                        + "  },\n"
                        + "  \"loudnessMetrics\": {\n"
                        + "    \"integratedLufs\": 浮点数（估算整体响度，如 -14.2，如果无法精确计算请凭听觉压迫感给出一个合理的负数估值）,\n"
                        + "    \"truePeakDbtp\": 浮点数（如 -1.0）,\n"
                        + "    \"loudnessRangeLra\": 浮点数（如 5.4）\n"
                        + "  },\n"
                        + "  \"auditoryTimeline\": [\n"
                        + "    {\n"
                        + "      \"timeRange\": { \"start\": 开始秒数, \"end\": 结束秒数 },\n"
                        + "      \"auditoryPerception\": { \"moodVibe\": \"情绪氛围\", \"energyLevel\": \"low/medium/high/peak\", \"acousticFeatures\": [\"特色乐器或音效1\", \"特色乐器2\"] },\n"
                        + "      \"bestMatchedSlot\": \"最适合用于视频的段落：hook/body/climax/outro\",\n"
                        + "      \"recommendedMaterial\": \"推荐搭配的视觉素材画面内容（如星空、夜景、缓慢推移等）\"\n"
                        + "    }\n"
                        + "  ],\n"
                        + "  \"mixDefaults\": {\n"
                        + "    \"defaultMixLevel\": \"QUIET / BALANCED / DRIVE（推荐在视频中的混音等级）\",\n"
                        + "    \"fadeInFrames\": 整数（推荐淡入帧数）,\n"
                        + "    \"fadeOutFrames\": 整数（推荐淡出帧数）,\n"
                        + "    \"duckingRatio\": 浮点数（推荐闪避系数 0.0 ~ 1.0）,\n"
                        + "    \"duckingRecommended\": 布尔值（有人声时是否推荐开启闪避）,\n"
                        + "    \"loopRecommended\": 布尔值（是否适合循环使用）\n"
                        + "  }\n"
                        + "}\n"
                        + "注意：如果无法精准识别物理数值（如 LUFS / BPM），请基于你的听感经验给出一个相对合理的估算值，不要留空。";
}
